apiVersion: v1
kind: Service
metadata:
  namespace: storefronts
  labels:
    app: {{ .Values.domainName }}
  name: {{ .Values.domainName }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /api/health
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.domainName }}
      port: 3004
      targetPort: 3004
  selector:
    app: {{ .Values.domainName }}


